### ISSUE TITLE
Set up continuous integration pipeline 🛠

### ISSUE THREAD

**Issue by thierrymarianne** [guillaume-rygn/Twitter-header-bot#11]
At the moment, the application is not blessed with automated testing, yet.

A pull-request [altering the core logic](https://github.com/guillaume-rygn/Twitter-header-bot/pull/3) quite a bit has been merged already,
and [another with less to worry about](https://github.com/guillaume-rygn/Twitter-header-bot/pull/9/files) (thanks to third-party tools robustness like prettier and eslint) are pending at the moment.

However, we might want to change this state for the best
by putting together a continuous integration pipeline.
Perhaps, GitHub actions would be enough here.

As a result, there are few options
 - [ ] [travis-ci](https://www.travis-ci.com/)
 - [ ] [circleCI](https://circleci.com/signup/)
 - [x] [GitHub Actions](https://fr.github.com/features/actions)
 - [ ] [Codeship](https://app.codeship.com/)
 - You name it (by commenting)?
 
We could take the opportunity offered by @TheGuit with https://github.com/guillaume-rygn/Twitter-header-bot/pull/8 to go one step further and having basic tests running,
hence preventing dreaded regressions.

**To begin with, I'd suggest that a single test run would be enough 
only for ensuring workflows or builds to be triggered on pull-request creation**

**Comment by guillaume-rygn** [comment]
I think that setting up a continuous integration pipeline would be a good thing, we can turn to _Github action_ which, as you say, is very easy to use !
